# Standards: 1.2
---
- name: Download repo key
  shell:
    cmd: curl -sSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor --output /usr/share/keyrings/microsoft-archive-keyring.gpg
    creates: /usr/share/keyrings/microsoft-archive-keyring.gpg
  tags:
    - vscode

- name: Add apt repository
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-archive-keyring.gpg] https://packages.microsoft.com/repos/vscode stable main
    filename: vscode
    update_cache: True
    state: present
  tags:
    - vscode

- name: Install required packages
  loop:
    - code
  package:
    name: "{{ item }}"
    state: present
  tags:
    - vscode

- name: Install defined extension
  loop: "{{ (vscode_general_users + vscode_extra_users) | subelements('extensions', skip_missing=True) }}"
  loop_control:
    label: "{{ item.0.username }}: {{ item.1.name | default(item.1) }}"
  when:
    - item.1.state | default('present') == 'present'
  register: vscode_ext_install
  become: True
  become_user: "{{ item.0.username }}"
  command: "{{ item.0.executable | default('code') }} --install-extension {{ item.1.name | default(item.1) }}"
  changed_when: "'was successfully installed' in vscode_ext_install.stdout"
  failed_when: vscode_ext_install.rc != 0
  tags:
    - vscode

- name: Remove defined extension
  loop: "{{ (vscode_general_users + vscode_extra_users) | subelements('extensions', skip_missing=True) }}"
  loop_control:
    label: "{{ item.0.username }}: {{ item.1.name | default(item.1) }}"
  when:
    - item.1.state | default('present') == 'absent'
  register: vscode_ext_remove
  become: True
  become_user: "{{ item.0.username }}"
  command: "{{ item.0.executable | default('code') }} --uninstall-extension {{ item.1.name | default(item.1) }}"
  changed_when: "'was successfully uninstalled' in vscode_ext_remove.stdout"
  failed_when: vscode_ext_install.rc != 0
  tags:
    - vscode

...
